sudo: required 
language: generic
services:
  - docker

before_install:
  - gem install rake
  - docker build  -t mbenkhal/docker-react -f Dockerfile.dev .

scripts:
  - docker run mbenkhal/docker-react npm run test -- --coverage 